import { ipcRenderer, contextBridge } from 'electron'

contextBridge.exposeInMainWorld('unreal', {
  getProjects: () => ipcRenderer.invoke('get-projects'),
  saveProject: (project: any) => ipcRenderer.invoke('save-project', project),
  selectProjectFile: () => ipcRenderer.invoke('select-project-file'),
  launchProject: (path: string) => ipcRenderer.invoke('launch-project', path),
  getEngines: () => ipcRenderer.invoke('get-engines'),
  addEnginePath: () => ipcRenderer.invoke('add-engine-path'),
  getConfigPaths: () => ipcRenderer.invoke('get-config-paths'),
  addProjectPath: () => ipcRenderer.invoke('add-project-path'),
  removePath: (type: 'engine' | 'project', path: string) => ipcRenderer.invoke('remove-path', type, path),
  launchEngine: (path: string) => ipcRenderer.invoke('launch-engine', path),
  getEnginePlugins: (path: string) => ipcRenderer.invoke('get-engine-plugins', path),
  updateProjectDetails: (path: string, details: any) => ipcRenderer.invoke('update-project-details', path, details),
  selectImage: () => ipcRenderer.invoke('select-image'),
  addProjectFile: () => ipcRenderer.invoke('add-project-file'),
  addDroppedProject: (path: string) => ipcRenderer.invoke('add-dropped-project', path),
  checkGitRepo: (path: string) => ipcRenderer.invoke('check-git-repo', path),
  getGitHistory: (path: string) => ipcRenderer.invoke('get-git-history', path),
  getGitStatus: (path: string) => ipcRenderer.invoke('get-git-status', path),
  // New v1.2 Features
  openProjectLog: (path: string) => ipcRenderer.invoke('open-project-log', path),
  generateProjectFiles: (path: string) => ipcRenderer.invoke('generate-project-files', path),
  cleanProjectCache: (path: string) => ipcRenderer.invoke('clean-project-cache', path),
  cloneProject: (path: string, newName: string) => ipcRenderer.invoke('clone-project', path, newName),
  readIniFile: (path: string) => ipcRenderer.invoke('read-ini-file', path),
  writeIniFile: (path: string, data: Record<string, any>) => ipcRenderer.invoke('write-ini-file', path, data),
  getProjectTags: () => ipcRenderer.invoke('get-project-tags'),
  saveProjectTags: (tags: Record<string, string[]>) => ipcRenderer.invoke('save-project-tags', tags),
  minimize: () => ipcRenderer.invoke('window-minimize'),
  maximize: () => ipcRenderer.invoke('window-maximize'),
  close: () => ipcRenderer.invoke('window-close'),
})
